### ISSUE TITLE
LibGuildRoster Init Issues

### ISSUE THREAD

**Issue by Sharlikran** [ESOUIMods/MasterMerchant#10]
@ghostbane38 unfortunately someone has an issue.

![image](https://user-images.githubusercontent.com/1912426/95407761-cbc87b00-08d2-11eb-8c65-331572cf5ef4.png)

Do you have a branch without the bulk copy? Not that I feel there is a specific reason but just that without the bulk copy as a starting point. Then do you have any ideas to make the initialization rock solid so that people don't have any possible hidden issues?

The user uses ATT and TTC. I will give them this link and ask them to post something.

**Comment by ghostbane38** [comment]
@Sharlikran 

I am already working on a better initialization.

Running MM alongside ATT? They would have already had problems in the past if the roster features of each was enabled, so this is very interesting.

ATT does not have LGR support released yet, which is a bit of an issue.

Would you like to forward this person on to me so I can debug with them directly?

**Comment by Mandragorane** [comment]
@ghostbane38
@Sharlikran

I have the same problem as the person above. I use all three addons as well to get a better idea about what's going on in the ESO markets lol.

Anyhow I had mine set to display only ATT info in the guild roster since I don't need all the info from MM (I know that taxes are 7% ;-) ). After installing Libguildroster it shifted all the ATT guild roster info to the right and I can't see the sales info. When enabling MM and ATT the information is overlapping. Looking at the ESOUI LibGuildRoster "About" page, there is an image showing that you could display both of them at the same time but maybe I'm misunderstanding it.

Now I'm forced to use MM info on the guild roster since MM is not working without this addon and I have to disable ATT on the guild roster. Not a biggy really but I'm losing the option...

**Comment by Sharlikran** [comment]
I will add a better explanation then since this looks like it is not really a bug, it is expected. I already mentioned that SGT would cause issues. So then it only makes sense that anything altering the guild roster has to have LGR support or it won't look right.

**Comment by Mandragorane** [comment]
As far as the guild roster MM is actually gives you more info :-) I just like ATT because its more condensed, personal preference.

For your last point not related to the guild roster info, I'm still using ATT because it can give me some info/options MM doesn't. And ofcourse I'm keeping MM because it has way more options ;-)

Just want to say again, thank you for taking on MM. I was trying to get a hold of Philgo for the last year or so w/o success and Im so glad that somebody picked it up !!!!

**Comment by ghostbane38** [comment]
@Mandragorane
@Sharlikran

LGR support is hopefully coming out in the next version of ATT. That screenshot on the LGR page is an amended version of ATT I made as a demo for the maintainer. It just illustrates of what it will look like once everyone, and everything is on board.

Unfortunately it will take X amount of time till the next version of ATT will be released. I will hit up the ATT maintainer again to see if I can get some idea.

**Comment by Mandragorane** [comment]
@Sharlikran

One more question, is there a reason why I can't post a comment on ESOUI MM 3.0? When I log in it states it's "closed" and I might not have  permission to post in this category? tx

**Comment by Sharlikran** [comment]
Because I want it closed. Github issues are not forums.

**Comment by Mandragorane** [comment]
Got it ! 
And sorry to bug you again: I'm sure you know that I can't post any comments, new ones or replies to other comments on the esoui mm site; not just the github issue. I'm assuming that is your Intention? tx

**Comment by ghostbane38** [comment]
Got word from Aldanga there, he has a version already made with support and is passing it off to his alpha testers. Looking at a hopeful release in a few days. This should resolve this issue.

**Comment by Mandragorane** [comment]
Cool, thanks :-)
